name: Metrics
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *'
  workflow_dispatch:
  push: { branches: ['main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, activity, community, metadata
          plugin_lines: yes
